### ISSUE TITLE
Make helper links open in a new tab

### ISSUE THREAD

**Issue by ParaBolt** [stefanjudis/tiny-helpers#276]
Basis : I was looking for different favicon generators at Tiny Helpers and decided to try to them all to see the different results they generate. I know I can always do an open in tab/window via a right-click but having it as the default behavior could be more convenient.

**Comment by stefanjudis** [comment]
Thank you ParaBolt, that's a tricky topic. 🙈 I agree that this can be useful for your case. 

Let me explain my primary use case: I usually go to tiny-helpers and know the tool I'm looking for. In that case, your desired behavior would lead to me open 2 tabs always. I don't know about a way to not open `target=_blank` in a new tab.

In the current situation, you can do `ctrl/cmd + click` or right-click to get your desired result quite easily. If we'd change to `target=_blank`, my desired result is not possible anymore. That's why I prefer to keep it as is. Happy to discuss and explain my standpoint further. 

Thanks for your contributions and this idea to make tiny helpers better. :)
